image: ubuntu

stages:
  - build
  - test
  - sonarqube
  - deploy

before_script:
  - echo "Start CI/CD Booker"

build:
  image: maven:latest
  stage: build
  script:
    - echo "Start 'Build process' "
    - cd Booker
    - mvn clean package -DskipTests
    - echo "Build process successfully done !"
  only:
    - master
  tags:
    - booker-runner

unit_tests:
  stage: test
  variables:      
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: root
    SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3302/bookerdb?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
  script:
    - echo "Start 'Test process' "
    - cd Booker
    - sudo docker run -p 127.0.0.1:3302:3306  --name test-db -e MYSQL_ROOT_PASSWORD=root -d mariadb:latest
    - mvn clean test
    - sudo docker stop test-db
    - sudo docker rm test-db -v
    - echo "Test process successfully done !"
  only:
    - master

  tags:
    - booker-runner

katalon_test_suite:
  stage: test
  script:
    - echo "start katalon test suite"
    # - katalon -noSplash  -runMode=console -consoleLog -projectPath=
    #       "<Your_Project_Directory>" -retry=0
    #       -testSuitePath="Test Suites/<Test_Suite_Name>" -executionProfile=
    #       "default" -browserType="Chrome (headless)"
    - echo "katalon test suite ok"
  only:
    - master
  tags:
    - booker-runner


sonarqube:
  stage: sonarqube
  variables:      
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: root
    SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3302/bookerdb?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
  script:
    - echo "start sonarqube upload to cloud"
    - sudo docker run -p 127.0.0.1:3302:3306  --name testing-db -e MYSQL_ROOT_PASSWORD=root -d mariadb:latest
    - cd Booker
    - mvn verify "org.sonarsource.scanner.maven:sonar-maven-plugin:sonar"
    - sudo docker stop testing-db
    - sudo docker rm testing-db -v
    - echo "sonarqube ok"
  only:
    - master
  tags:
    - booker-runner




deploy_ssh:
  stage: deploy
  script:
    - echo "Start 'Deployment process' "
    - sudo docker-compose down --remove-orphans
    - sudo docker-compose up -d --build
    - sudo docker-compose ps
    - echo "Deployment successfull !"
  only:
    - master
  tags:
    - booker-runner
  when: manual

after_script:
  - echo "End CI/CD for Booker"
