version: '3'
services:
  mysql-db:
    image: mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend  

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - mysql-db
    ports:
      - 8080:8080
    networks:
      - backend 
      - frontend
        
  spring-app:
    container_name: spring-app
    build: .
    restart: on-failure
    ports:
      - "8088:8088"
    depends_on: 
      - mysql-db  
    environment:      
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db/bookerdb?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    command: mvn clean spring-boot:run
    networks:
      - backend
      - frontend

  katalon-executor:
    container_name: katalon-executor
    build: ./Katalon/Booker-Kat
    ports: 
      - "8888:8088"
    volumes:
      - .:/


volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:   
